/**
 * Jest config for unit tests only — no live database required.
 * Run the full suite (including integration tests) with `npm test`.
 */
const base = require('./jest.config.js');

module.exports = {
  ...base,
  testPathIgnorePatterns: [
    '/node_modules/',
    'tests/alter-table\\.test\\.ts',
    'tests/alter-table-complex\\.test\\.ts',
    'tests/auto-configure\\.test\\.ts',
    'tests/auto-sql\\.test\\.ts',
    'tests/check-table-exists\\.test\\.ts',
    'tests/create-table\\.test\\.ts',
    'tests/create-table-complex\\.test\\.ts',
    'tests/database-connection\\.test\\.ts',
    'tests/database-error-handling\\.test\\.ts',
    'tests/database-retry\\.test\\.ts',
    'tests/get-table-metadata\\.test\\.ts',
    'tests/index-query-builder\\.test\\.ts',
    'tests/query-validation\\.test\\.ts',
    'tests/test-split-table\\.test\\.ts',
    'tests/exponent-column\\.test\\.ts',
    'tests/schema-history-db\\.test\\.ts',
    'tests/transaction-atomicity\\.test\\.ts',
    'tests/stream-injection\\.test\\.ts',
    'tests/schema-override\\.test\\.ts',
    'tests/staging-primary-key\\.test\\.ts',
    'tests/surrogate-key-live\\.test\\.ts',
    'tests/autoincrement-upsert-live\\.test\\.ts',
    'tests/encoding-roundtrip-live\\.test\\.ts',
    'tests/large-data-live\\.test\\.ts',
    'tests/timestamps-external-table-live\\.test\\.ts',
    'tests/assume-schema-live\\.test\\.ts',
    'tests/column-widening-live\\.test\\.ts',
    'tests/orphan-staging-live\\.test\\.ts',
    'tests/tinyint-roundtrip-live\\.test\\.ts',
    'tests/reingest-idempotent-live\\.test\\.ts',
    'tests/add-column-existing-live\\.test\\.ts',
    'tests/all-null-column-live\\.test\\.ts',
    'tests/existing-schema-live\\.test\\.ts',
    'tests/bulk-load-live\\.test\\.ts',
    'tests/boolean-inference-live\\.test\\.ts',
    'tests/stream-small-int-live\\.test\\.ts',
    'tests/no-credential-logging-live\\.test\\.ts',
    'tests/charset-upgrade-live\\.test\\.ts',
    'tests/sqlserver-live\\.test\\.ts',
    'tests/number-like-fidelity-live\\.test\\.ts',
  ],
};
